# Generated by Django 2.2.1 on 2019-05-29 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='KeepTrack',
        ),
    ]
