# Generated by Django 2.2.1 on 2019-05-29 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part1', '0003_film_viewers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='viewers',
            field=models.ManyToManyField(related_name='films', to='part1.Viewer'),
        ),
    ]
